name: kdtree
version: 0.0.2
description: A basic super fast Dart implementation of the k-dimensional (k-d) tree data structure.
homepage: https://github.com/JankoLancer/kd-tree-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
